[mod] update ovs-dump scripts

diff --git a/usertools/ovs-dump b/usertools/ovs-dump
--- a/usertools/ovs-dump
+++ b/usertools/ovs-dump
@@ -19,7 +19,7 @@ function start_capture()
 		exit 1;
 	fi
 
-	/usr/bin/dpdk-pdump -- --pdump device_id=$pci,queue=*,rx-dev=lo,tx-dev=lo --server-socket-path=/usr/local/var/run/openvswitch &
+	/usr/bin/dpdk-pdump --file-prefix ovs-$OVS_MODE -- --pdump device_id=$pci,queue=*,rx-dev=lo,tx-dev=lo --server-socket-path=/usr/local/var/run/openvswitch &
 	if [ $? != 0 ] ; then
 	    echo -e "\e[1;31mdpdk-dump start failed\e[0m"
 		exit 1;
@@ -46,6 +46,15 @@ function stop_capture()
 	    echo -e "\e[1;31mdpdk-dump stoped failed\e[0m"
 	fi
 }
+
+conf_file=/etc/openvswitch/ovs-dpdk.conf
+
+if test -e $conf_file; then  
+	source $conf_file
+else
+	echo -e "\e[1;31mERROR Could not find ovs-dpdk.conf \e[0m"
+	exit 1;
+fi
 
 if [ $# != 2 ] ; then 
 	echo -e "\e[1;32mUSAGE: $0 DPDK_PORT_NAME [start/stop]\e[0m"
