[mod] update on-line deploy scripts

diff --git a/usertools/ovs_pre_check b/usertools/ovs_pre_check
--- a/usertools/ovs_pre_check
+++ b/usertools/ovs_pre_check
@@ -5,7 +5,7 @@
 logdir='/usr/local/var/log/openvswitch'
 rundir='/usr/local/var/run/openvswitch'
 sysconfdir='/etc'
-etcdir='$sysconfdir/openvswitch'     
+etcdir='$sysconfdir/openvswitch'	 
 datadir='/usr/local/share/openvswitch'
 dbdir='/usr/local/etc/openvswitch'
 bindir='/usr/bin'
@@ -17,197 +17,301 @@ DB_FILE=$dbdir/conf.db
 DB_SOCK=$rundir/db.sock
 DB_SCHEMA=$datadir/vswitch.ovsschema
 
-KERNEL_VERSION="3.10.0-514.16.1.chishui01.x86_64"
-QEMU_VERSION="qemu-kvm-ev"
-
-# 2*vf_port To support hot-upgrade
-SRIOV_NUM=2
-
-# 2*1024 To support hot-upgrade
-NR_HUGEPAGES=2048
-
 osCheck()
 {
-    echo -e "\e[1;32m[ovs-dpdk] Checking system version \e[0m" 	
-    echo ""	
+	echo -e "\e[1;32m[ovs-dpdk] Checking system version \e[0m"	
+	echo ""	
 
-    sysOS=`uname -r`
+	sysOS=`uname -r`
 
-    if [ $sysOS == $KERNEL_VERSION ]; then
-        echo -e "\e[1;32m[ovs-dpdk] System OS version is expected \e[0m" 	
-        echo ""	
-    else
-        echo -e "\e[1;31m[ovs-dpdk] $HOST System OS version supposed be $KERNEL_VERSION \e[0m"
-        echo ""	
-        exit -1
-    fi
+	if [ $sysOS == $KERNEL_VERSION ]; then
+		echo -e "\e[1;32m[ovs-dpdk] System OS version is expected \e[0m"	
+		echo ""	
+	else
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: $HOST System OS version supposed be $KERNEL_VERSION \e[0m"
+		echo ""	
+		exit -1
+	fi
+}
+
+pkgCheck()
+{
+	echo -e "\e[1;32m[ovs-dpdk] Checking essential pkg \e[0m"	
+	echo ""	
+
+	rpm -qa | grep $IGB_PKG &>/dev/null
+
+	if [ $? -ne 0 ]; then
+		echo -e "\e[1;32m[ovs-dpdk] ERROR: $IGB_PKG is not installed yet, starting to install \e[0m"	
+		echo ""
+		rpm -ivh $IGB_PKG 2>>/dev/null
+		if [ $? -ne 0 ]; then
+			echo -e "\e[1;32m[ovs-dpdk] ERROR: $IGB_PKG is installation failed \e[0m"	
+			echo ""
+			exit -1
+		else
+			echo -e "\e[1;32m[ovs-dpdk] $IGB_PKG is already installed \e[0m"	
+			echo ""
+		fi
+	else
+		echo -e "\e[1;32m[ovs-dpdk] $IGB_PKG is already installed \e[0m"	
+		echo ""
+	fi
+
+	rpm -qa | grep $I40E_PKG &>/dev/null
+
+	if [ $? -ne 0 ]; then
+		echo -e "\e[1;32m[ovs-dpdk] ERROR: $I40E_PKG is not installed yet, starting to install \e[0m"	
+		echo ""
+		rpm -ivh $I40E_PKG 2>>/dev/null
+		if [ $? -ne 0 ]; then
+			echo -e "\e[1;32m[ovs-dpdk] ERROR: $I40E_PKG is installation failed \e[0m"	
+			echo ""
+			exit -1
+		else
+			echo -e "\e[1;32m[ovs-dpdk] $I40E_PKG is already installed \e[0m"	
+			echo ""
+		fi
+	else
+		echo -e "\e[1;32m[ovs-dpdk] $I40E_PKG is already installed \e[0m"	
+		echo ""
+	fi
 }
 
 iommuCheck()
 {
-    dmesg | grep -e DMAR -e IOMMU > /dev/null
-    if [ $? -ne 0 ] ; then
-        echo -e "\e[1;32m[ovs-dpdk] VT-d supposed enabled in the BIOS \e[0m"
-        echo ""	
-        exit -1
-    fi
+	dmesg | grep -e DMAR -e IOMMU > /dev/null
+	if [ $? -ne 0 ] ; then
+		echo -e "\e[1;32m[ovs-dpdk] VT-d supposed enabled in the BIOS \e[0m"
+		echo ""	
+		exit -1
+	fi
 
-    iommu=`cat /proc/cmdline | grep iommu=pt`
-    intel_iommu=`cat /proc/cmdline | grep intel_iommu=on`
-    if [[ $iommu && $intel_iommu ]];then
-        echo -e "\e[1;32m[ovs-dpdk] VT-d is enabled in the kernel \e[0m"
-        echo ""	
-    else
-        echo -e "\e[1;31m[ovs-dpdk] VT-d not enabled in the kernel \e[0m"
-        echo ""	
-        exit -1
-    fi
+	iommu=`cat /proc/cmdline | grep iommu=pt`
+	intel_iommu=`cat /proc/cmdline | grep intel_iommu=on`
+	if [[ $iommu && $intel_iommu ]];then
+		echo -e "\e[1;32m[ovs-dpdk] VT-d is enabled in the kernel \e[0m"
+		echo ""	
+	else
+		echo -e "\e[1;31m[ovs-dpdk] VT-d not enabled in the kernel \e[0m"
+		echo ""	
+		exit -1
+	fi
 }
 
 numaCheck()
 {
-    isNuma=`lscpu |grep "NUMA node(s):" |awk '{print $NF}'`
-    if [ $isNuma -eq 1 ]; then
-        echo -e "\e[1;31m[ovs-dpdk] NUMA is not enabled , to operate \e[0m"
-        echo ""	
-    else
-        echo -e "\e[1;32m[ovs-dpdk] NUMA is enabled in the kernel \e[0m"
-        echo ""	
-    fi
-    
+	isNuma=`lscpu |grep "NUMA node(s):" |awk '{print $NF}'`
+	if [ $isNuma -eq 1 ]; then
+		echo -e "\e[1;31m[ovs-dpdk] NUMA is not enabled , to operate \e[0m"
+		echo ""	
+	else
+		echo -e "\e[1;32m[ovs-dpdk] NUMA is enabled in the kernel \e[0m"
+		echo ""	
+	fi
+	
 }
 
 threadCheck()
 {
-    cores=`lscpu |grep "Thread(s) per core" | awk '{print $NF}'`
-    if [ $cores -eq 2 ]; then
-        echo -e "\e[1;32m[ovs-dpdk] Hyper-Threading is enabled in the kernel \e[0m"
-        echo ""	
-    else
-        echo -e "\e[1;31m[ovs-dpdk] Hyper-Threading is not enabled in the kernel \e[0m"
-        echo ""	
-        exit -1
-    fi
+	cores=`lscpu |grep "Thread(s) per core" | awk '{print $NF}'`
+	if [ $cores -eq 2 ]; then
+		echo -e "\e[1;32m[ovs-dpdk] Hyper-Threading is enabled in the kernel \e[0m"
+		echo ""	
+	else
+		echo -e "\e[1;31m[ovs-dpdk] Hyper-Threading is not enabled in the kernel \e[0m"
+		echo ""	
+		exit -1
+	fi
 }
 
 qemuCheck()
 {
-    rpm -qa | grep $QEMU_VERSION > /dev/null
-    if [ $? -ne 0 ] ; then
-        echo -e "\e[1;31m[ovs-dpdk] Qemu Version supposed be $QEMU_VERSION \e[0m"
-        echo ""	
-        exit -1
-    fi
+	rpm -qa | grep $QEMU_VERSION > /dev/null
+	if [ $? -ne 0 ] ; then
+		echo -e "\e[1;31m[ovs-dpdk] Qemu Version supposed be $QEMU_VERSION \e[0m"
+		echo ""	
+		exit -1
+	fi
 }
 
 hugepageCheck()
 {
-    grep -s "$mountdir" /proc/mounts > /dev/null
-    if [ $? -ne 0 ] ; then
-        mount -t hugetlbfs none $mountdir
-    fi
+	grep -s "$mountdir" /proc/mounts > /dev/null
+	if [ $? -ne 0 ] ; then
+		mount -t hugetlbfs none $mountdir
+	fi
 
-    echo $NR_HUGEPAGES > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
-    echo $NR_HUGEPAGES > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages
+	echo $NR_HUGEPAGES > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
+	echo $NR_HUGEPAGES > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages
 
-    pagesize=`awk '/Hugepagesize/ {print $2}' /proc/meminfo`
-    pagetotal=`awk '/HugePages_Total/ {print $2} ' /proc/meminfo`
-    if [ $pagesize -a $pagetotal ] ; then
-        echo -e "\e[1;32m[ovs-dpdk] Hugepage size : $pagesize Hugepage Total : $pagetotal \e[0m"
-        echo ""	
-    else
-        echo -e "\e[1;31m[ovs-dpdk] Mount Hugepage failed \e[0m"
-        echo ""	
-        exit -1
-    fi
+	pagesize=`awk '/Hugepagesize/ {print $2}' /proc/meminfo`
+	pagetotal=`awk '/HugePages_Total/ {print $2} ' /proc/meminfo`
+	if [ $pagesize -a $pagetotal ] ; then
+		echo -e "\e[1;32m[ovs-dpdk] Hugepage size : $pagesize Hugepage Total : $pagetotal \e[0m"
+		echo ""	
+	else
+		echo -e "\e[1;31m[ovs-dpdk] Mount Hugepage failed \e[0m"
+		echo ""	
+		exit -1
+	fi
 }
 
 toolsCheck()
 {
-    if [ ! -f "$sbindir/dpdk-devbind" ]; then
-        yum install dpdk-tools.x86_64 -y > /dev/null
-    fi
+	if [ ! -f "$sbindir/dpdk-devbind" ]; then
+		yum install dpdk-tools.x86_64 -y > /dev/null
+	fi
 
-    if [ ! -f "$sbindir/dpdk-devbind" ]; then
-        echo -e "\e[1;31m[ovs-dpdk] dpdk-devbind tools uninstalled \e[0m"
-        echo ""	
-        exit -1
-    else
-        echo -e "\e[1;32m[ovs-dpdk] dpdk-devbind tools installed \e[0m"
-        echo ""	
-    fi
+	if [ ! -f "$sbindir/dpdk-devbind" ]; then
+		echo -e "\e[1;31m[ovs-dpdk] dpdk-devbind tools uninstalled \e[0m"
+		echo ""	
+		exit -1
+	else
+		echo -e "\e[1;32m[ovs-dpdk] dpdk-devbind tools installed \e[0m"
+		echo ""	
+	fi
 }
 
 sriovCheck()
 {
-    device=`ip route show default | awk '/default/ {print $5}'`
-    if [[ $device ]];then
-    	dev_num=`cat /sys/class/net/$device/device/sriov_numvfs`
-    	lspci | grep 'Virtual Function' > /dev/null
-   	if [ $? -ne 0 ] ; then
-    		echo $SRIOV_NUM > /sys/class/net/$device/device/sriov_numvfs
-		
-		for((var = 0; var < $SRIOV_NUM; var++)
-		do
-    			ip link set $device vf $var spoofchk off
-		done
+	device=`ip route show default | awk '/default/ {print $5}'`
+	if [[ $device ]];then
+		dev_num=`cat /sys/class/net/$device/device/sriov_numvfs`
+		lspci | grep 'Virtual Function' > /dev/null
+		if [ $? -ne 0 ] ; then
+			echo $SRIOV_NUM > /sys/class/net/$device/device/sriov_numvfs
+			
+			for ((var = 0; var < $SRIOV_NUM; var++))
+			do
+				ip link set $device vf $var spoofchk off
+			done
+		fi
+	else
+		echo -e "\e[1;31m[ovs-dpdk] NIC num is not expected \e[0m"
+		echo ""	
+		exit -1
 	fi
-    else
-    	echo -e "\e[1;31m[ovs-dpdk] NIC num is not expected \e[0m"
-    	echo ""	
-    	exit -1
-    fi
 }
 
 vfioCheck()
 {
-    $sbindir/dpdk-devbind --status | grep "drv=vfio-pci" > /dev/null
-    if [ $? -eq 0 ] ; then
-        echo -e "\e[1;32m[ovs-dpdk] VFIO module bond VF port success \e[0m"
-        return 1
-    fi
+	$sbindir/dpdk-devbind --status | grep "drv=vfio-pci" > /dev/null
+	if [ $? -eq 0 ] ; then
+		echo -e "\e[1;32m[ovs-dpdk] VFIO module bond VF port success \e[0m"
+		return 1
+	fi
 
-    modprobe vfio-pci
+	modprobe vfio-pci
 
-    /sbin/lsmod | grep -s vfio_pci > /dev/null
-    if [ $? -ne 0 ] ; then
-        echo -e "\e[1;31m[ovs-dpdk] VFIO module modprobe failed \e[0m"
-        echo ""	
-        exit -1
-    else
-        echo -e "\e[1;32m[ovs-dpdk] VFIO module modprobe success \e[0m"
-        echo ""	
-    fi
+	/sbin/lsmod | grep -s vfio_pci > /dev/null
+	if [ $? -ne 0 ] ; then
+		echo -e "\e[1;31m[ovs-dpdk] VFIO module modprobe failed \e[0m"
+		echo ""	
+		exit -1
+	else
+		echo -e "\e[1;32m[ovs-dpdk] VFIO module modprobe success \e[0m"
+		echo ""	
+	fi
 
-    /usr/bin/chmod a+x /dev/vfio
-    /usr/bin/chmod 0666 /dev/vfio/*
+	/usr/bin/chmod a+x /dev/vfio
+	/usr/bin/chmod 0666 /dev/vfio/*
 
-    vf_pci=`lspci |grep X710|grep  Virtual | gawk '{print $1}' | sed -n '1p'`
-    if [[ $vf_pci ]];then
-        $sbindir/dpdk-devbind --bind=vfio-pci $vf_pci
-    else
-        echo -e "\e[1;31m[ovs-dpdk] VF Port num is not expected \e[0m"
-        echo ""	
-        exit -1
-    fi
+	vf_pci=`lspci |grep X710|grep  Virtual | gawk '{print $1}' | sed -n '1p'`
+	if [[ $vf_pci ]];then
+		$sbindir/dpdk-devbind --bind=vfio-pci $vf_pci
+	else
+		echo -e "\e[1;31m[ovs-dpdk] VF Port num is not expected \e[0m"
+		echo ""	
+		exit -1
+	fi
 
-    $sbindir/dpdk-devbind --status | grep "drv=vfio-pci" > /dev/null
-    if [ $? -ne 0 ] ; then
-        echo -e "\e[1;31m[ovs-dpdk] VFIO module bonding VF port failed \e[0m"
-        echo ""	
-        exit -1
-    else
-        echo -e "\e[1;32m[ovs-dpdk] VFIO module bonding VF port success \e[0m"
-        echo ""	
-    fi
+	$sbindir/dpdk-devbind --status | grep "drv=vfio-pci" > /dev/null
+	if [ $? -ne 0 ] ; then
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: VFIO module bonding VF port failed \e[0m"
+		echo ""	
+		exit -1
+	else
+		echo -e "\e[1;32m[ovs-dpdk] VFIO module bonding VF port success \e[0m"
+		echo ""	
+	fi
 }
 
+uioCheck()
+{
+	if [ ! -f /lib/modules/`uname -r`/kernel/net/igb-uio/igb_uio.ko ];then
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: Target does not have the DPDK UIO Kernel Module. \e[0m"
+		echo -e "\e[1;31m[ovs-dpdk] 	To fix, please try to yum install from didirepo.\e[0m"
+		exit -1
+	fi
+
+	$sbindir/lsmod | grep -s uio > /dev/null
+	if [ $? -ne 0 ] ; then
+		modinfo uio > /dev/null
+		if [ $? -eq 0 ]; then
+			echo -e "\e[1;31m[ovs-dpdk] Loading uio module \e[0m"
+			echo ""
+			sudo $sbindir/modprobe uio
+		fi
+	fi
+
+	echo -e "\e[1;32m[ovs-dpdk] Loading DPDK UIO module \e[0m"
+	echo ""
+	sudo $sbindir/modprobe igb_uio
+	if [ $? -ne 0 ] ; then
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: Could not load kernel/net/igb-uio/igb_uio.ko. \e[0m"
+		exit -1
+	fi
+
+	echo -e "\e[1;32m[ovs-dpdk] Loaded kernel/net/igb-uio/igb_uio.ko. \e[0m"
+	echo ""
+}
+
+bindCheck()
+{
+	$sbindir/dpdk-devbind --status | grep "drv=igb_uio" > /dev/null
+	if [ $? -eq 0 ] ; then
+		echo -e "\e[1;32m[ovs-dpdk] IGB_UIO module bond VF port success \e[0m"
+		return 1
+	fi
+
+	vf_pci1=`lspci |grep X710|grep  Virtual | gawk '{print $1}' | sed -n '1p'`
+	vf_pci2=`lspci |grep X710|grep  Virtual | gawk '{print $1}' | sed -n '2p'`
+	if [[ $vf_pci1 && $vf_pci1 ]];then
+		$sbindir/dpdk-devbind --bind=igb_uio $vf_pci1
+	else
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: VF Port num is not expected \e[0m"
+		echo ""	
+		exit -1
+	fi
+
+	$sbindir/dpdk-devbind --status | grep "drv=igb_uio" > /dev/null
+	if [ $? -ne 0 ] ; then
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: IGB_UIO module bonding VF port failed \e[0m"
+		echo ""	
+		exit -1
+	else
+		echo -e "\e[1;32m[ovs-dpdk] IGB_UIO module bonding VF port success \e[0m"
+		echo ""	
+	fi
+}
 
 echo
 echo '===== OVS-DPDK Pre Check ====='
 echo
 
+conf_file=/etc/openvswitch/ovs-dpdk.conf
+
+if test -e $conf_file; then  
+	source $conf_file
+else
+	echo -e "\e[1;31m[ovs-dpdk] ERROR Could not find ovs-dpdk.conf \e[0m"
+	echo ""	
+	exit -1
+fi
+
 osCheck
+pkgCheck
 iommuCheck
 numaCheck
 threadCheck
@@ -215,7 +319,9 @@ qemuCheck
 hugepageCheck
 toolsCheck
 sriovCheck
-vfioCheck
+#vfioCheck
+uioCheck;
+bindCheck;
 
 echo
 echo '===== END ====='
diff --git a/usertools/ovs_start b/usertools/ovs_start
--- a/usertools/ovs_start
+++ b/usertools/ovs_start
@@ -5,7 +5,7 @@
 logdir='/usr/local/var/log/openvswitch'
 rundir="/usr/local/var/run/openvswitch"
 sysconfdir='/etc'
-etcdir='$sysconfdir/openvswitch'     
+etcdir='$sysconfdir/openvswitch'	 
 scriptdir='/usr/local/share/openvswitch/scripts/'
 datadir='/usr/local/share/openvswitch'
 dbdir='/usr/local/etc/openvswitch'
@@ -16,58 +16,69 @@ DB_FILE=$dbdir/conf.db
 DB_SOCK=$rundir/db.sock
 DB_SCHEMA=$datadir/vswitch.ovsschema
 
-PKG=$1
-KERNEL_VERSION="3.10.0-514.16.1.chishui01.x86_64"
-
 ovsCheck()
 {
-    echo -e "\e[1;32m[ovs-dpdk] Checking system version \e[0m" 	
-    echo ""	
+	echo -e "\e[1;32m[ovs-dpdk] Checking system version \e[0m"	
+	echo ""	
 
-    sysOS=`uname -r`
+	sysOS=`uname -r`
 
-    if [ $sysOS == $KERNEL_VERSION ]; then
-        echo -e "\e[1;32m[ovs-dpdk] System OS version is Correct \e[0m" 	
-        echo ""	
-    else
-        echo -e "\e[1;31m[ovs-dpdk] $HOST System OS version supposed be $KERNEL_VERSION \e[0m"
-        echo ""	
-        exit -1
-    fi
+	if [ $sysOS == $KERNEL_VERSION ]; then
+		echo -e "\e[1;32m[ovs-dpdk] System OS version is Correct \e[0m"		
+		echo ""	
+	else
+		echo -e "\e[1;31m[ovs-dpdk] ERROR: $HOST System OS version supposed be $KERNEL_VERSION \e[0m"
+		echo ""	
+		exit -1
+	fi
 }
 
 pkgCheck()
 {
-    echo -e "\e[1;32m[ovs-dpdk] Checking ovs-dpdk package \e[0m" 	
-    echo ""	
+	echo -e "\e[1;32m[ovs-dpdk] Checking ovs-dpdk package \e[0m"	
+	echo ""	
 
-    rpm -qa | grep $PKG &>/dev/null
+	rpm -qa | grep $PKG &>/dev/null
 
-    if [ $? -ne 0 ]; then
-        echo -e "\e[1;32m[ovs-dpdk] $PKG is not installed yet, starting to install \e[0m" 	
-        echo ""
-        rpm -ivh $PKG 2>>/dev/null
-        if [ $? -ne 0 ]; then
-            echo -e "\e[1;32m[ovs-dpdk] $PKG is installation failed \e[0m" 	
-            echo ""
-            exit -1
-        else
-            echo -e "\e[1;32m[ovs-dpdk] $PKG is already installed \e[0m" 	
-            echo ""
-        fi
-    else
-        echo -e "\e[1;32m[ovs-dpdk] $PKG is already installed \e[0m" 	
-        echo ""
-    fi
+	if [ $? -ne 0 ]; then
+		echo -e "\e[1;32m[ovs-dpdk] ERROR: $PKG is not installed yet, starting to install \e[0m"	
+		echo ""
+		rpm -ivh $PKG 2>>/dev/null
+		if [ $? -ne 0 ]; then
+			echo -e "\e[1;32m[ovs-dpdk] ERROR: $PKG is installation failed \e[0m"	
+			echo ""
+			exit -1
+		else
+			echo -e "\e[1;32m[ovs-dpdk] $PKG is already installed \e[0m"	
+			echo ""
+		fi
+	else
+		echo -e "\e[1;32m[ovs-dpdk] $PKG is already installed \e[0m"	
+		echo ""
+	fi
 }
 
 echo
 echo '===== OVS-DPDK Start ====='
 echo
 
+conf_file=/etc/openvswitch/ovs-dpdk.conf
+
+if test -e $conf_file; then  
+	source $conf_file
+else
+	echo -e "\e[1;31m[ovs-dpdk] ERROR Could not find ovs-dpdk.conf \e[0m"
+	echo ""	
+	exit -1
+fi
+
 osCheck
 pkgCheck
-$scriptdir/ovs-ctl start
+$scriptdir/ovs-ctl --system-id=random start
+
+/usr/local/bin/tnl_set_arp br-dpdk
+sleep 5
+supervisorctl update
 
 echo
 echo '===== END ====='
